export const dataPotion = [
  {
    nameTH: 'ยาเพิ่ม HP เล็กน้อย',
    nameEN: 'Red Potion',
    price: 20,
    image: '/potion/red-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเพิ่ม HP น้อย',
    nameEN: 'Orange Potion',
    price: 20,
    image: '/potion/orange-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเพิ่ม HP กลาง',
    nameEN: 'Yellow Potion',
    price: 30,
    image: '/potion/yellow-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเพิ่ม HP มาก',
    nameEN: 'White Potion',
    price: 60,
    image: '/potion/white-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเพิ่ม SP',
    nameEN: 'Blue Potion',
    price: 40,
    image: '/potion/blue-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาแก้พิษ',
    nameEN: 'Green Potion',
    price: 50,
    image: '/potion/green-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเร่งเล็ก',
    nameEN: 'Concentration Potion',
    price: 100,
    image: '/potion/concentration-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเร่งกลาง',
    nameEN: 'Awakening Potion',
    price: 200,
    image: '/potion/awakening-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเร่งใหญ่',
    nameEN: 'Berserk Potion',
    price: 300,
    image: '/potion/berserk-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเด้ง HP เล็ก',
    nameEN: 'Small Life Potion',
    price: 100,
    image: '/potion/small-life-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาเด้ง HP กลาง',
    nameEN: 'Medium Life Potion',
    price: 200,
    image: '/potion/medium-life-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'ยาป้องกัน',
    nameEN: 'Big Defense Potion',
    price: 300,
    image: '/potion/big-defense-potion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
];

export const dataWeapon = [
  {
    nameTH: 'Pole Axe',
    nameEN: 'Pole Axe',
    price: 500,
    image: '/spear/pole-axe.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Long Horn',
    nameEN: 'Long Horn',
    price: 600,
    image: '/spear/long-horn.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Thanatos spear',
    nameEN: 'Thanatos spear',
    price: 700,
    image: '/spear/thanos-spear.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Adulter Fides Guardian Spear',
    nameEN: 'Adulter Fides Guardian Spear',
    price: 800,
    image: '/spear/adulter-fides-guardian-spear.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Dagger',
    nameEN: 'Dagger',
    price: 300,
    image: '/dagger/dagger.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Damascus',
    nameEN: 'Damascus',
    price: 400,
    image: '/dagger/damascus.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Combat Knife',
    nameEN: 'Combat Knife',
    price: 500,
    image: '/dagger/combat-knife.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Assasin Dagger',
    nameEN: 'Assasin Dagger',
    price: 600,
    image: '/dagger/assasin-dagger.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Swords',
    nameEN: 'Swords',
    price: 1000,
    image: '/sword/swords.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Falchion',
    nameEN: 'Falchion',
    price: 1100,
    image: '/sword/falchion.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Blade',
    nameEN: 'Blade',
    price: 1200,
    image: '/sword/blade.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Adulter Fidews Guardian Sword',
    nameEN: 'Adulter Fidews Guardian Sword',
    price: 1300,
    image: '/sword/adulter-fides-guardian.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Swords',
    nameEN: 'Swords',
    price: 1000,
    image: '/sword2/swords.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Broad',
    nameEN: 'Broad',
    price: 1100,
    image: '/sword2/broad.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Claymore',
    nameEN: 'Claymore',
    price: 1200,
    image: '/sword2/claymore.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Muramasa',
    nameEN: 'Muramasa',
    price: 1300,
    image: '/sword2/muramasa.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
];

export const dataArmor = [
  {
    nameTH: 'Shirt',
    nameEN: 'Shirt',
    price: 100,
    image: '/shirt/shirt.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Adventure Suit',
    nameEN: 'Adventure Suit',
    price: 200,
    image: '/shirt/adventure-suit.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Assassin Robe',
    nameEN: 'Assassin Robe',
    price: 300,
    image: '/shirt/assassin-robe.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Chain Mail',
    nameEN: 'Chain Mail',
    price: 400,
    image: '/shirt/chain-mail.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Angel Spirit',
    nameEN: 'Angel Spirit',
    price: 1000,
    image: '/head/angel-spirit.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Angel Wing',
    nameEN: 'Angel Wing',
    price: 2000,
    image: '/head/angel-wing.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Angel Wing Ears',
    nameEN: 'Angel Wing Ears',
    price: 3000,
    image: '/head/angel-wing-ears.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Baphomet Horns',
    nameEN: 'Baphomet Horns',
    price: 4000,
    image: '/head/baphomet-horns.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Hood',
    nameEN: 'Hood',
    price: 100,
    image: '/garment/hood.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Clock Of Survival',
    nameEN: 'Clock Of Survival',
    price: 200,
    image: '/garment/clock-of-survival.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Diablo Healinium',
    nameEN: 'Diablo Healinium',
    price: 300,
    image: '/garment/diablo-healinium.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
];

export const dataCard = [
  {
    nameTH: 'Abysmal Knight Card',
    nameEN: 'Abysmal Knight Card',
    price: 5000,
    image: '/card/abysmal-knight.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Alice Card',
    nameEN: 'Alice Card',
    price: 3000,
    image: '/card/alice.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
  {
    nameTH: 'Andre Card',
    nameEN: 'Andre Card',
    price: 500,
    image: '/card/andre.png',
    quantity: 100,
    cost: 5,
    available: true,
  },
];
